# Macro file for example B2

# Change the default number of workers (in multi-threading mode) 
/run/numberOfThreads 1
#
# Initialize kernel
/run/initialize

/tracking/verbose 1
#
# 1 event with printing hits
#
/tracking/verbose 0
/hits/verbose 2
#
# set target and chamber material
#
/gun/particle e-
/gun/energy 300 MeV
/B2/det/setTargetMaterial G4_WATER
/B2/det/setChamberMaterial G4_Ar
/run/beamOn 1

