# Setup the right LCG environment
source /cvmfs/sft.cern.ch/lcg/views/LCG_105a/x86_64-el9-gcc12-opt/setup.sh

# source /cvmfs/lhcb.cern.ch/lib/LbEnv

# Setup some environment variables

# General Vaiables
export BINARY_TAG="x86_64_v3-el9-gcc12+cuda12_1-opt+g"
export STACK_ROOT="/afs/cern.ch/work/j/jbenavid/private/workspace/stack"
export CUDA_ARCHITECTURE=75

export BUILD_FORMAT="build.$BINARY_TAG"
export INSTALL_FORMAT="InstallArea/$BINARY_TAG"

# Gaussino
export GAUSSINO_ROOT="$STACK_ROOT/Gaussino"
export GAUSSINO_BUILD="$GAUSSINO_ROOT/$BUILD_FORMAT"
export GAUSSINO_INSTALL="$GAUSSINO_ROOT/$INSTALL_FORMAT"
export GAUSSINO_RUN="$GAUSSINO_ROOT/run"

# Geant4
export GEANT4_ROOT="$STACK_ROOT/Geant4"
export GEANT4_BUILD="$GEANT4_ROOT/$BUILD_FORMAT"
export GEANT4_INSTALL="$GEANT4_ROOT/$INSTALL_FORMAT"

export GEANT4_DATA_DIR=/cvmfs/lhcb.cern.ch/lib/lhcb/PARAM/Geant4Files/v107r1/data
export G4NEUTRONHPDATA=$GEANT4_DATA_DIR/G4NDL4.6
export G4LEDATA=$GEANT4_DATA_DIR/G4EMLOW7.13
export G4LEVELGAMMADATA=$GEANT4_DATA_DIR/PhotonEvaporation5.7
export G4RADIOACTIVEDATA=$GEANT4_DATA_DIR/RadioactiveDecay5.6
export G4PARTICLEXSDATA=$GEANT4_DATA_DIR/G4PARTICLEXS3.1.1
export G4PIIDATA=$GEANT4_DATA_DIR/G4PII1.3
export G4REALSURFACEDATA=$GEANT4_DATA_DIR/RealSurface2.2
export G4SAIDXSDATA=$GEANT4_DATA_DIR/G4SAIDDATA2.0
export G4ABLADATA=$GEANT4_DATA_DIR/G4ABLA3.1
export G4INCLDATA=$GEANT4_DATA_DIR/G4INCL1.0
export G4ENSDFSTATEDATA=$GEANT4_DATA_DIR/G4ENSDFSTATE2.3

# VecCore
export VECCORE_ROOT="$STACK_ROOT/VecCore"
export VECCORE_BUILD="$VECCORE_ROOT/$BUILD_FORMAT"
export VECCORE_INSTALL="$VECCORE_ROOT/$INSTALL_FORMAT"

# VecGeom
export VECGEOM_ROOT="$STACK_ROOT/VecGeom"
export VECGEOM_BUILD="$VECGEOM_ROOT/$BUILD_FORMAT"
export VECGEOM_INSTALL="$VECGEOM_ROOT/$INSTALL_FORMAT"

# G4HepEM
export G4HEPEM_ROOT="$STACK_ROOT/G4HepEM"
export G4HEPEM_BUILD="$G4HEPEM_ROOT/$BUILD_FORMAT"
export G4HEPEM_INSTALL="$G4HEPEM_ROOT/$INSTALL_FORMAT"

# AdePT
export ADEPT_ROOT="$STACK_ROOT/AdePT"
export ADEPT_BUILD="$ADEPT_ROOT/$BUILD_FORMAT"
export ADEPT_INSTALL="$ADEPT_ROOT/$INSTALL_FORMAT"

